MVCCivicaEmployeeMaster/Controllers/ReportController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MVCCivicaEmployeeMaster.Infrastructure;
using MVCCivicaEmployeeMaster.ViewModel;
using MVCCivicaEmployeeMaster.ViewModels;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Globalization;
using System.Reflection;
namespace MVCCivicaEmployeeMaster.Controllers
{
    public class ReportController : Controller
    {
        private readonly IHttpClientService _httpClientService;
        private readonly IConfiguration _configuration;


        private string endPoint;

        public ReportController(IHttpClientService httpClientService, IConfiguration configuration)
        {
            _httpClientService = httpClientService;
            _configuration = configuration;
            endPoint = _configuration["EndPoint:CivicaApi"];

        }

        public IActionResult YearlySalaryReport()
        {
            var model = new SalaryHeadTotal();
            model.Year = DateTime.Now.Year; // Set default year to current year

            // Adjust the range for the dropdown to include years from 2001 to 2024
            ViewBag.YearList = Enumerable.Range(2001, 2024).ToList();

            return View(model);
        }


        // POST: /Salary/YearlySalaryReport
        [HttpPost]
        public IActionResult YearlySalaryReport(int year)
        {
          
            var apiUrl = $"{endPoint}Employee/GetTotalSalaryByYear?year={year}";
            var response = _httpClientService.GetHttpResponseMessage<SalaryHeadTotal>(apiUrl, HttpContext.Request);


            if (response.IsSuccessStatusCode)
            {
                string data = response.Content.ReadAsStringAsync().Result;
                Console.WriteLine(data);
                var jsonObject = JsonConvert.DeserializeObject<JObject>(data);

                // Extract the 'data' array from the JSON object
                var dataArray = jsonObject["data"].ToObject<JArray>();

                // Deserialize 'data' array into a list of SalaryHeadTotal objects

                var serviceResponse = dataArray.ToObject<List<SalaryHeadTotal>>();

                if (serviceResponse != null && serviceResponse.Count > 0)
                {
                    decimal totalBasicSalary = serviceResponse.Sum(s => s.BasicSalary);
                    decimal totalHRA = serviceResponse.Sum(s => s.HRA);
                    decimal totalAllowance = serviceResponse.Sum(s => s.Allowance);
                    decimal totalGrossSalary = serviceResponse.Sum(s => s.GrossSalary);
                    decimal totalPfDeduction = serviceResponse.Sum(s => s.PfDeduction);
                    decimal totalProfTax = serviceResponse.Sum(s => s.ProfTax);
                    decimal totalGrossDeductions = serviceResponse.Sum(s => s.GrossDeductions);
                    decimal totalTotalSalary = serviceResponse.Sum(s => s.TotalSalary);


                    var model = new SalaryHeadTotal
                    {
                        BasicSalary = totalBasicSalary,
                        HRA = totalHRA,
                        Allowance = totalAllowance,
                        GrossSalary = totalGrossSalary,
                        PfDeduction = totalPfDeduction,
                        ProfTax = totalProfTax,
                        GrossDeductions = totalGrossDeductions,
                        TotalSalary = totalTotalSalary
                    };
                    return View("YearlySalaryReport", model);
                }
                return View("YearlySalaryReport");


            }
            else
            {
                TempData["ErrorMessage"] = "No data available for this year.";
                return RedirectToAction("YearlySalaryReport");
            }

        }


        public IActionResult MonthalyProfTaxReport()
        {
            var model = new SalaryHeadTotal();
            model.Year = DateTime.Now.Year; // Set default year to current year

            // Prepare a list to hold year and month combinations
            List<SelectListItem> yearMonthList = new List<SelectListItem>();

            // Loop through each year from 2001 to the current year
            for (int year = 2001; year <= DateTime.Now.Year; year++)
            {
                // Loop through each month from 1 to 12
                for (int month = 1; month <= 12; month++)
                {
                    // Create a SelectListItem for each month in each year
                    SelectListItem item = new SelectListItem
                    {
                        Value = $"{year}-{month.ToString("00")}", // Format: "yyyy-MM" (e.g., "2024-07")
                        Text = $"{year} - {CultureInfo.CurrentCulture.DateTimeFormat.GetMonthName(month)}"
                    };
                    yearMonthList.Add(item);
                }
            }

            // Assign the list to ViewBag
            ViewBag.YearMonthList = yearMonthList;

            return View(model);
        }

        // POST: /Salary/YearlySalaryReport
        [HttpPost]
        public IActionResult MonthalyProfTaxReport(int year, int month)
        {
           
            if(year==DateTime.Now.Year && month > DateTime.Now.Month)
            {
                TempData["ErrorMessage"] = "Please select past month.";
                var emptyModel = new SalaryHeadTotal(); // Or fetch an appropriate empty model
                return View(emptyModel);
            }
            if (year < 2000 || month < 0)
            {
                TempData["ErrorMessage"] = "Please select both year and month.";
                var emptyModel = new SalaryHeadTotal(); // Or fetch an appropriate empty model
                return View(emptyModel);
            }
            var apiUrl = $"{endPoint}Employee/GetTotalSalaryByMonth?month={month}&year={year}";
            var response = _httpClientService.GetHttpResponseMessage<SalaryHeadTotal>(apiUrl, HttpContext.Request);


            if (response.IsSuccessStatusCode)
            {
                string data = response.Content.ReadAsStringAsync().Result;
                Console.WriteLine(data);
                var jsonObject = JsonConvert.DeserializeObject<JObject>(data);

                // Extract the 'data' array from the JSON object
                var dataArray = jsonObject["data"].ToObject<JArray>();

                // Deserialize 'data' array into a list of SalaryHeadTotal objects

                var serviceResponse = dataArray.ToObject<List<SalaryHeadTotal>>();

                if (serviceResponse != null && serviceResponse.Count > 0)
                {

                    decimal totalProfTax = serviceResponse.Sum(s => s.ProfTax);



                    var model = new SalaryHeadTotal
                    {

                        ProfTax = totalProfTax,

                    };
                    return View("MonthalyProfTaxReport", model);
                }
                return View("MonthalyProfTaxReport");


            }
            else
            {
                TempData["ErrorMessage"] = "No data available for this year.";
                return RedirectToAction("MonthalyProfTaxReport");
            }

        }


        public IActionResult YearlyEachEmpSalaryReport(int id)
        {
            var model1 = new SalaryHeadTotal();
            model1.Year = DateTime.Now.Year; // Set default year to current year

            // Adjust the range for the dropdown to include years from 2001 to 2024
            ViewBag.YearList = Enumerable.Range(2001, 2024).ToList();
            ViewBag.empId = id;
            //model1.Id = id;

            return View(model1);
        }



        // POST: /Salary/YearlyEachEmpSalaryReport
        [HttpPost]
        public IActionResult YearlyEachEmpSalaryReport(int year, int id)
        {
           var apiUrl = $"{endPoint}Employee/GetTotalSalaryByYearAndId/{id},{year}";
                var response = _httpClientService.GetHttpResponseMessage<SalaryHeadTotal>(apiUrl, HttpContext.Request);

                if (response.IsSuccessStatusCode)
                {
                    string data = response.Content.ReadAsStringAsync().Result;
                    var jsonObject = JsonConvert.DeserializeObject<JObject>(data);

                    // Extract the 'data' array from the JSON object
                    var dataArray = jsonObject["data"].ToObject<JArray>();

                    // Deserialize 'data' array into a list of SalaryHeadTotal objects
                    var serviceResponse = dataArray.ToObject<List<SalaryHeadTotal>>();

                    if (serviceResponse != null && serviceResponse.Count > 0)
                    {
                        decimal totalBasicSalary = serviceResponse.Sum(s => s.BasicSalary);
                        decimal totalHRA = serviceResponse.Sum(s => s.HRA);
                        decimal totalAllowance = serviceResponse.Sum(s => s.Allowance);
                        decimal totalGrossSalary = serviceResponse.Sum(s => s.GrossSalary);
                        decimal totalPfDeduction = serviceResponse.Sum(s => s.PfDeduction);
                        decimal totalProfTax = serviceResponse.Sum(s => s.ProfTax);
                        decimal totalGrossDeductions = serviceResponse.Sum(s => s.GrossDeductions);
                        decimal totalTotalSalary = serviceResponse.Sum(s => s.TotalSalary);

                        var model = new SalaryHeadTotal
                        {
                            BasicSalary = totalBasicSalary,
                            HRA = totalHRA,
                            Allowance = totalAllowance,
                            GrossSalary = totalGrossSalary,
                            PfDeduction = totalPfDeduction,
                            ProfTax = totalProfTax,
                            GrossDeductions = totalGrossDeductions,
                            TotalSalary = totalTotalSalary
                        };

MVCCivicaEmployeeMaster/Views/Report/MonthalyProfTaxReport.cshtml
@using MVCCivicaEmployeeMaster.ViewModel
@using System.Globalization
@model SalaryHeadTotal

@{
    ViewData["Title"] = "Monthaly ProfTax Report ";
}
<div class="card mb-3">
    <div class="card-body">
        <partial name="_AllEmployeesView" />
        <div class="card mb-3" id="proftax">
            <div class="card-body btn-light">
                <h1 class="card-title text-center">Monthly ProfTax Report</h1>


                @using (Html.BeginForm("MonthalyProfTaxReport", "Report", FormMethod.Post, new { id = "monthlyReportForm" }))
                {
                    <div class="form-group">
                        @Html.Label("Select Year:")
                        @{
                            var currentYear = DateTime.Now.Year;
                            var yearList = Enumerable.Range(2001, currentYear - 2000).Reverse()
                            .Select(x => new SelectListItem
                {
                    Text = x.ToString(),
                    Value = x.ToString()
                });
                            var selectListYear = new SelectList(yearList, "Value", "Text", null);
                        }
                        @Html.DropDownList("year", selectListYear, "Select Year", new { @class = "form-control", onchange = "showMonthDropdown()" })
                    </div>

                    <div class="form-group" id="monthDropdown" style="display: none;">
                        @Html.Label("Select Month:")
                        @{
                            var monthList = Enumerable.Range(1, 12)
                            .Select(x => new SelectListItem
                {
                    Text = CultureInfo.CurrentCulture.DateTimeFormat.GetMonthName(x),
                    Value = x.ToString()
                });
                            var selectListMonth = new SelectList(monthList, "Value", "Text", null);
                        }
                        @Html.DropDownList("month", selectListMonth, "Select Month", new { @class = "form-control", onchange = "submitForm()" })
                        
                    </div>


                }
                <div id="yearErrorMessage" style=" color: red;">*Please select a year.</div>
                <div id="monthErrorMessage" style="color: red;">*Please select a month.</div>
            </div>
        </div>
        <div class="row">
            <div class="col-3 text-start">
                <a class="btn btn-secondary btn-block " asp-action="MonthlySalaryReport" asp-controller="Report">
                    <i class="fas fa-arrow-left"></i> Back to List
                </a>
            </div>
        </div>
    </div>
</div>

@if (Model != null && Model.ProfTax != 0)
{
    <div class="card mb-3">
        <div class="card-body">

            <table class="table">
                <thead>
                    <tr>
                        <th>Prof Tax</th>

                    </tr>
                </thead>
                <tbody>
                    <tr>

                        <td>@Model.ProfTax</td>

                    </tr>
                </tbody>
            </table>
        </div>
    </div>
}

@if (TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger">@TempData["ErrorMessage"]</div>
}

@section Scripts {
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script type="text/javascript">

        function submitForm() {
            var selectedMonth = $('#month').val();
            if (selectedMonth !==''){
                $('#monthErrorMessage').hide();
                $('#monthlyReportForm').submit();
            }else{
                $('#monthErrorMessage').show();
            }
        };

        function monthForError(){
            var selectedMonth = $('#month').val();
            if (selectedMonth !== '') {
                $('#monthErrorMessage').hide();
            } else {
                $('#monthErrorMessage').show();
            }
        }

        $(document).ready(function () {
            // Function to show month dropdown if year is selected
            function showMonthDropdown() {
                var selectedYear = $('#year').val();
                var selectedMonth = $('#month').val();
                
                if (selectedYear !== '') {
                    $('#yearErrorMessage').hide();
                    $('#monthDropdown').show();
                } else {
                    $('#yearErrorMessage').show();
                    $('#monthDropdown').hide(); // Hide dropdown if no year is selected
                }
                if (selectedYear === '' && selectedMonth === '') {
                    $('#monthErrorMessage').hide();
                }
                if (selectedYear !== '' && selectedMonth !== '') {
                    $('#monthErrorMessage').hide();
                }

            }

            // Initial check on page load
            showMonthDropdown();

            $('#year').change(function () {
                showMonthDropdown();
                monthForError();
            });
        });
    </script>
}

MVCCivicaEmployeeMaster/Views/Report/MonthlyEachEmpSalaryReport.cshtml
@using MVCCivicaEmployeeMaster.ViewModel
@using System.Globalization
@model SalaryHeadTotal

@{
    ViewData["Title"] = "Monthly Salary Report";
}

<div class="card mb-3">
    <div class="card-body">
        <partial name="_EachEmployeeView" />
        <h1 class="card-title">Monthly Salary Report</h1>
        <div class="card mb-3" style="background-color:white">
            <div class="card-body" style="background-color:white">
                @using (Html.BeginForm("MonthlyEachEmpSalaryReport", "Report", FormMethod.Post, new { id = "monthlyReportForm" }))
                {
                    @Html.Hidden("id", null, new { id = "id" }) <!-- Hidden input field for Employee ID -->

                    <div class="form-group" style="background-color:white">
                        <label style="font-weight: bold;">Select Year:</label>
                        @{
                            var currentYear = DateTime.Now.Year;
                            var yearList = Enumerable.Range(2001, currentYear - 2000).Reverse()
                            .Select(x => new SelectListItem
                {
                    Text = x.ToString(),
                    Value = x.ToString()
                });
                            var selectListYear = new SelectList(yearList, "Value", "Text", null);
                        }
                        @Html.DropDownList("year", selectListYear, "Select Year", new { @class = "form-control", onchange = "showMonthDropdown()" })
                    </div>

                    <div class="form-group" id="monthDropdown" style="display: none;">
                        @Html.Label("Select Month:")
                        @{
                            var monthList = Enumerable.Range(1, 12)
                            .Select(x => new SelectListItem
                {
                    Text = CultureInfo.CurrentCulture.DateTimeFormat.GetMonthName(x),
                    Value = x.ToString()
                });
                            var selectListMonth = new SelectList(monthList, "Value", "Text", null);
                        }
                        @Html.DropDownList("month", selectListMonth, "Select Month", new { @class = "form-control", onchange = "checkMonthForError()" })
                        <div id="monthErrorMessage" style="display: none; color: red;">Please select a month.</div>
                        
                    </div>
                }

                @* Error message for Year selection *@
                @* <div id="yearErrorMessage" @* class="alert alert-danger"  style="display: none;">*Please select a year.</div> *@
            <div id="yearErrorMessage" style="display: none; color: red;">*Please select a year.</div>
                
            </div>
        </div>

        @if (Model != null && Model.TotalSalary != 0)
        {
            <div class="card mb-3" >
                <div class="card-body" id="salarySlipTable">
                    <table class="table table-striped">
                        <thead>
                        <th scope="col" class="text-uppercase">Sr No.</th>
                        <th scope="col" class="text-uppercase">Salary Head</th>
                        <th scope="col" colspan="2" class="text-uppercase text-end">Amount</th>
                        </thead>
                        <tbody class="table-group-divider">
                            <tr>
                                <th scope="row">1</th>
                                <td>Basic Salary</td>

                                <td class="text-end" colspan="2">@Model.BasicSalary</td>
                            </tr>
                            <tr>
                                <th scope="row">2</th>
                                <td>HRA</td>
                                <td class="text-end" colspan="2">@Model.HRA</td>

                            </tr>
                            <tr>
                                <th scope="row">3</th>
                                <td>Allowance</td>
                                <td class="text-end" colspan="2">@Model.Allowance</td>

                            </tr>
                            <tr>
                                <th scope="row">4</th>
                                <td>Gross Salary</td>
                                <td class="text-end" colspan="2">@Model.GrossSalary</td>

                            </tr>

                            <tr>
                                <td colspan="3" class="text-end">PF Deduction</td>
                                <td class="text-end">@Model.PfDeduction</td>
                            </tr>
                            <tr>
                                <td colspan="3" class="text-end">Prof Tax</td>
                                <td class="text-end">@Model.ProfTax</td>
                            </tr>
                            <tr>
                                <td colspan="3" class="text-end">Gross Deductions</td>
                                <td class="text-end">@Model.GrossDeductions</td>
                            </tr>
                            <tr>
                                <th scope="row" colspan="3" class="text-uppercase text-end">Total Salary</th>
                                <td class="text-end">@Model.TotalSalary</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>

            <div class="row">
                <div class="col-12 text-end">
                    <button type="submit" class="btn btn-primary mb-3" onclick="downloadSalarySlip()">Download Salary Slip</button>
                </div>
            </div>

            <div class="row">
                <div class="col-3 text-start">
                    <a class="btn btn-secondary btn-block " asp-action="EachEmployeeGrid" asp-controller="Report">
                        <i class="fas fa-arrow-left"></i> Back to List
                    </a>
                </div>
            </div>
        }
    </div>
</div>

@section Scripts {
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.5.3/jspdf.debug.js" integrity="sha384-NaWTHo/8YCBYJ59830LTz/P4aQZK1sS0SneOgAvhsIl3zBu8r9RevNg5lHCHAuQ/" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/0.4.1/html2canvas.min.js"></script>
    <script type="text/javascript">
        function checkMonthForError() {
            let selectedMonth = $('#month').val();
            if (selectedMonth !== '') {
                $('#monthErrorMessage').hide();
                $('#monthlyReportForm').submit();

            }
            else {
                $('#monthErrorMessage').show();
            }

        };

        function downloadSalarySlip() {
            const element = document.getElementById('salarySlipTable');


            html2canvas(element, {
                onrendered: function (canvas) {
                    const imgData = canvas.toDataURL('image/png');
                    const pdf = new jsPDF();
                    const imgProps = pdf.getImageProperties(imgData);
                    const pdfWidth = pdf.internal.pageSize.getWidth();
                    const pdfHeight = imgProps.height * pdfWidth / imgProps.width;
                    pdf.addImage(imgData, 'PNG', 0, 10, pdfWidth - 20, pdfHeight);
                    pdf.save('EmpMonthalysalary_slip.pdf');
                }
            });
        }
        $(document).ready(function () {
            // Function to show month dropdown if year is selected
            function showMonthDropdown() {
                let selectedYear = $('#year').val();
                let selectedMonth = $('#month').val();
                if (selectedYear !== '') {
                    $('#monthDropdown').show();
                    $('#monthErrorMessage').show();
                    $('#yearErrorMessage').hide(); // Hide year error message
                } else {
                    $('#monthDropdown').hide(); // Hide month dropdown if no year is selected
                    $('#yearErrorMessage').show(); // Show year error message
                }
                if (selectedMonth !== '') {
                    $('#monthErrorMessage').hide();
                    
                }
                
            }

            
            

            // Initial check on page load
            showMonthDropdown();

            // Handle form submission
            $('#monthlyReportForm').submit(function () {
                var selectedYear = $('#year').val();
                if (selectedYear === '') {
                    $('#yearErrorMessage').show(); // Show year error message
                    return false; // Prevent form submission
                }

                // Optionally, you can submit the selected month along with the form
                var selectedMonth = $('#month').val();
                if (selectedMonth !== '') {
                    $('<input />').attr('type', 'hidden')
                        .attr('name', "month")
                        .attr('value', selectedMonth)
                        .appendTo('#monthlyReportForm');
                }

                // Ensure the month dropdown is visible after submission if a year is selected
                showMonthDropdown();
            });

            // Handle change in year dropdown
            $('#year').change(function () {
                showMonthDropdown();
            });
        });
    </script>
}


        

MVCCivicaEmployeeMaster/Views/Report/ReportDecider.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

MVCCivicaEmployeeMaster/Views/Report/YearlySalaryReport.cshtml
@using MVCCivicaEmployeeMaster.ViewModel
@model SalaryHeadTotal

@{
    ViewData["Title"] = "Yearly Salary Report";
}

<div class="card mb-3">
    <div class="card-body">
        <partial name="_AllEmployeesView" />

        <div class="card mb-3" id="yearly">
            <div class="card-body btn-light">
                <h1 class="card-title text-center">Yearly Salary Report</h1>
                @using (Html.BeginForm("YearlySalaryReport", "Report", FormMethod.Post, new { id = "yearlyReportForm" }))
                {
                    <div class="form-group">
                        <label style="font-weight: bold;">Select Year:</label>
                        @{
                            var currentYear = DateTime.Now.Year;
                            var yearList = Enumerable.Range(2001, currentYear - 2000).Reverse()
                            .Select(x => new SelectListItem
                {
                    Text = x.ToString(),
                    Value = x.ToString()
                });
                            var selectListYear = new SelectList(yearList, "Value", "Text", null);
                        }
                        @Html.DropDownList("year", selectListYear, "Select Year", new { @class = "form-control", onchange = "submitForm()" })
                    </div>
                }
                <div id="yearErrorMessage" style=" color: red;">*Please select a year.</div>
            </div>
        </div>

        @if (Model != null && Model.TotalSalary != 0)
        {
            <div class="card mb-3">
                <div class="card-body" id="salarySlipTable">
                    <table class="table table-striped">
                        <thead>
                        <th scope="col" class="text-uppercase">Sr No.</th>
                        <th scope="col" class="text-uppercase">Salary Head</th>
                        <th scope="col" colspan="2" class="text-uppercase text-end">Amount</th>
                        </thead>
                        <tbody class="table-group-divider">
                            <tr>
                                <th scope="row">1</th>
                                <td>Basic Salary</td>

                                <td class="text-end" colspan="2">@Model.BasicSalary</td>
                            </tr>
                            <tr>
                                <th scope="row">2</th>
                                <td>HRA</td>
                                <td class="text-end" colspan="2">@Model.HRA</td>

                            </tr>
                            <tr>
                                <th scope="row">3</th>
                                <td>Allowance</td>
                                <td class="text-end" colspan="2">@Model.Allowance</td>

                            </tr>
                            <tr>
                                <th scope="row">4</th>
                                <td>Gross Salary</td>
                                <td class="text-end" colspan="2">@Model.GrossSalary</td>

                            </tr>

                            <tr>
                                <td colspan="3" class="text-end">PF Deduction</td>
                                <td class="text-end">@Model.PfDeduction</td>
                            </tr>
                            <tr>
                                <td colspan="3" class="text-end">Prof Tax</td>
                                <td class="text-end">@Model.ProfTax</td>
                            </tr>
                            <tr>
                                <td colspan="3" class="text-end">Gross Deductions</td>
                                <td class="text-end">@Model.GrossDeductions</td>
                            </tr>
                            <tr>
                                <th scope="row" colspan="3" class="text-uppercase text-end">Total Salary</th>
                                <td class="text-end">@Model.TotalSalary</td>
                            </tr>
                        </tbody>
                    </table>
                    <div class="row">
                        <div class="col-12 text-end">
                            <button type="submit" class="btn btn-primary mb-3" onclick="downloadSalarySlip()">Download Salary Slip</button>
                        </div>
                    </div>
                </div>
            </div>
        }



        <div class="row">
            <div class="col-3 text-start">
                <a class="btn btn-secondary btn-block " asp-action="MonthlySalaryReport" asp-controller="Report">
                    <i class="fas fa-arrow-left"></i> Back to List
                </a>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.5.3/jspdf.debug.js" integrity="sha384-NaWTHo/8YCBYJ59830LTz/P4aQZK1sS0SneOgAvhsIl3zBu8r9RevNg5lHCHAuQ/" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/0.4.1/html2canvas.min.js"></script>

    <script type="text/javascript">

        $(document).ready(function () {
            var selectedYear = $('#year').val();
            if (selectedYear !== '') {
                $('#yearErrorMessage').hide();
            } else {
                $('#yearErrorMessage').show();
            }
        });


        function submitForm() {
            var selectedYear = $('#year').val();
            if (selectedYear !== '') {
                $('#yearErrorMessage').hide();
                $('#yearlyReportForm').submit();
            } else {
                $('#yearErrorMessage').show();
            }
        }



        function downloadSalarySlip() {
            const element = document.getElementById('salarySlipTable');


            html2canvas(element, {
                onrendered: function (canvas) {
                    const imgData = canvas.toDataURL('image/png');
                    const pdf = new jsPDF();
                    const imgProps = pdf.getImageProperties(imgData);
                    const pdfWidth = pdf.internal.pageSize.getWidth();
                    const pdfHeight = imgProps.height * pdfWidth / imgProps.width;
                    pdf.addImage(imgData, 'PNG', 5, 10, pdfWidth - 50, pdfHeight - 50);
                    pdf.save('salary_slip.pdf');
                }
            });
        }
    </script>


}

<style>
    .card {
        border: 1px solid rgba(0, 0, 0, 0.125);
        border-radius: 0.25rem;
        margin-bottom: 20px;
    }

    #yearly {
        margin: 10px;
        margin-right: 5px;
        margin-left: 0px;
        padding-left: 0px;
    }
</style>